---
- name: Check if server keypair exists
  stat:
    path: "{{ wg_conf_dir.path }}/privatekey"
  register: wg_privatekey_exist

- name: Generate wireguard server keypair
  shell: >
    bash -c "set -euxo pipefail;
    umask 077 && wg genkey | tee {{ wg_conf_dir.path }}/privatekey |
    wg pubkey > {{ wg_conf_dir.path }}/publickey"
  when: not wg_privatekey_exist.stat.exists
