---
- name: Update aptitude
  apt:
    upgrade: full
    update_cache: true
    autoclean: true
    autoremove: true

- name: Add wireguard repository
  apt_repository:
    repo: "ppa:wireguard/wireguard"
    state: present

- name: Install wireguard
  apt:
    name: "wireguard"
    state: present
