---
- name: Update aptitude
  apt:
    upgrade: full
    update_cache: true
    autoclean: true
    autoremove: true

# - name: Add wireguard repository
#   apt_repository:
#     repo: "ppa:wireguard/wireguard"
#     state: present

- name: Install wireguard
  apt:
    name: "wireguard"
    state: present

- name: Install pip3
  apt:
    name: python3-pip
    update_cache: yes
    state: present

- name: Install boto3 of pip3
  pip:
    name: boto3

# For Ubuntu minimal 19.04 and later
- name: Check iptables is present
  stat:
    path: "/usr/sbin/iptables"
  register: check_iptables

- name: Install iptables
  apt:
    name: "iptables"
    state: present
  when: "not check_iptables.stat.exists"
