- name: Install pip
  apt:
    name: python3-pip
    update_cache: yes
    state: present
- pip:
    name: boto3
- name: upload key config vpn to s3
  s3_sync:
    bucket: "{{ bucket }}"
    key_prefix: credentials/wireguard
    file_root: "{{ wg_conf_dir.path }}/{{ item.value.username }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    exclude: "privatekey"
  with_dict : "{{ wg_user_list }}"
  when: (item.value.remove == false)