- name: upload key config vpn to s3
  s3_sync:
    bucket: "{{ s3_bucket }}"
    key_prefix: "{{ s3_key_prefix }}"
    file_root: "{{ wg_conf_dir.path }}/{{ item.value.username }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"
    region: "{{ region }}"
    exclude: "privatekey"
  with_dict : "{{ wg_user_list }}"
  when: (item.value.remove == false)
