---
- name: start wg0
  systemd:
    name: "wg-quick@wg0"
    state: started
    enabled: true
    daemon_reload: true

- name: restart wg0
  systemd:
    name: "wg-quick@wg0"
    state: restarted
    daemon_reload: true
